### ISSUE TITLE
Need policy decision on urn values for Iliadic cit elements

### ISSUE THREAD

**Issue by neelsmith** [homermultitext/hmt-editors-guide#16]
Suggestion:  check whether cited passage matches text of this manuscript.  If so, cite to version level;  if not, cite to notional Iliad.

For analysis of text reuse, the first case is a "direct quote of extant text";  the second case is a multiform.

**Comment by StephanieML** [comment]
we don't know for sure if the scribe is referencing the text of the manuscript or if the matching readings are coincidental. If we want to cite on the version level, I think it would make sense to have a way of citing it to the version of the Iliad as appears in the scholia, but not as appears in the manuscript. Or we could keep it as notional and keep our analysis separate.

**Comment by neelsmith** [comment]
I don't think we have to read the scribe's  mind:  if the text matches 
the Iliad text of the MS, then it IS legitimate to cite it at the 
version level.  If it doesn't match, I'm fine with citing it at the 
notional work level.

This is appealing to me in part because it would give us an entirely 
automated way to distinguish multiforms from citations of the same 
text:  so reading our minds, rather than the scribes!

**Comment by StephanieML** [comment]
I see the appeal for sure, but I still question whether it's something we want as part of the edition because we might be implying something about the scholia, their contents, and their sources that we don't necessarily want to.

If we're already classifying other `q`s by type, why would it be problematic to do the `cit` ones the same way?

**Comment by neelsmith** [comment]
Legitimate question!  We need to bring this up with Casey, Mary and Chris.

**Comment by neelsmith** [comment]
For now at least, follow Stephanie's suggestion:  all URNs at notional work level, with furhter analysis cleanly separated in a stand-off document.  Closing this issue.
