### ISSUE TITLE
New abbreviation for editors giude

### ISSUE THREAD

**Issue by juliaspiegel** [homermultitext/hmt-editors-guide#20]
We found a new abbreviation for εν on urn:cts:greekLit:tlg0012.tlg001.msA:24.312r.  Image: urn:cite:hmt:vaimg.VA312RN-0482@0.1848,0.6546,0.0089,0.0071.  It would be helpful if it were added to the editors guide and the paleographic guide.

**Comment by neelsmith** [comment]
This is an issue for the paleographic, not the guide to markup practice.

**Comment by neelsmith** [comment]
this should be closed here as soon as the corresponding issue is filed elsewhere.

**Comment by StephanieML** [comment]
filed on palguide issue tracker
