### ISSUE TITLE
How to categorize scholion partially in exterior margin

### ISSUE THREAD

**Issue by cshanley18** [homermultitext/hmt-editors-guide#21]
On 315v, at the top left of the page, there is a list of 4 items (πέπλος, χιτών, φᾶρος, χλαίνη), each with a brief description. Each item has its own row, with the item in the exterior margin and the description in the region of main scholia. Should these be considered as one main scholion?

**Comment by StephanieML** [comment]
There is markup for lists everything gets wrapped in the element 'list' and each row in the list gets the element 'item'. If this isn't in the editors guide, please put an issue on it.

**Comment by StephanieML** [comment]
And yes, this should be edited as one main scholion
