### ISSUE TITLE
Uses of del for scribal deletion

### ISSUE THREAD

**Issue by neelsmith** [homermultitext/hmt-editors-guide#33]
If we have del on a scribal deletion within a lexical token, I assume we need to wrap the token in `w` (as documented for `add` in the current guide).

But the example in the guide has `del` on a whole line, including a proper name that I think *should* have been tagged.  So in this instance `del` is wrapping tokens, while in the first, token marker `w` is wrapping `del`.

That could be OK, maybe, but we need examples of both at least.

**Comment by StephanieML** [comment]
I agree, I will look through the archive for examples

**Comment by StephanieML** [comment]
added
