### ISSUE TITLE
Suggestion: clarifying expansions of abbreviated forms

### ISSUE THREAD

**Issue by cdryan16** [homermultitext/hmt-editors-guide#7]
An abbreviation is necessary whenever a word form is shortened ambiguously.

How to expand: When providing an expansion, supply any appropriate breathings or accents which are precluded by the abbreviation.

The following is the name Aristophanes:
Citation: urn:cite:hmt:vaimg.VA137VN-0639@0.3706,0.2877,0.043,0.0152
This would be written as:
abbr: Ἀρτιστοφα
expan: Ἀριστοφάνης

**Comment by StephanieML** [comment]
resolved in latest push

**Comment by neelsmith** [comment]
Should we close this issue then?

**Comment by StephanieML** [comment]
yes
